### ISSUE TITLE
Cannot receive any updates.

### ISSUE THREAD

**Issue by awdr74100** [butthx/tgsnake#134]
First of all, I want to thank you for developing such a great package! I found this to be the easiest to use of all the telegram node packages.

I found that listening to a channel with more frequent updates will result in not listening to any messages after 2 minutes, while channels with less frequent updates do not have this problem and can keep running 24 hours a day. This problem exists in gramjs, tgsnake, and mtkruto, and I suspect it may be related to the library's internal implementations of UpdatesTooLong and getDifference, do you have any thoughts on this?

**Comment by butthx** [comment]
Hi, Thank you for using tgsnake before. Let me conclude, that you cannot receive updates from channels that send messages too frequently? 

If so, can you help me by sending the logs (set log level to debug) that appear? or you can give me the username of the channel so I can debug what's going on. You can PM me on telegram [t.me/butthx](https://t.me/butthx) to maintain privacy or some crucial data.

**Comment by awdr74100** [comment]
@butthx Hi sir, I think I may have found the reason, the average number of people online in my group is 3000, there are 10 messages every 1 second, the telegram client will always show your requests to join the group was approved, I guess it is possible that the library's internal implementation for the beginning of the listening to bind all the current existence of all the chat groups, and due to the amount of messages of a group is too large to cause the group reboot, the library's internal implementation can not listen to this reboot of the group, it's all my speculation!

```ts
import { Snake } from "tgsnake";

async function init() {
  const apiId = +"00000000";
  const apiHash = "00000000000000000000000000000000";

  const client = new Snake({
    apiId,
    apiHash,
    login: {},
    logLevel: "debug",
  });

  client.run();

  client.on("message", (ctx) => {
    console.log(`${Date.now()}`);
    console.log(ctx);
  });
}

init();
```

![螢幕擷取畫面 2024-04-01 233854](https://github.com/tgsnake/tgsnake/assets/47501692/f03c6eaa-9a41-427f-9c29-f098155e2692)

```text
(@tgsnake/core) debug - [3] Receive 132 bytes data 1/4/2024 22:43:10.103
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:10.103
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:10.103
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:10.104
(@tgsnake/core) debug - [10] Reading TLObject with id: 8c88c923 (Raw.UpdateChannelUserTyping) 1/4/2024 22:43:10.105
(@tgsnake/core) debug - [10] Reading TLObject with id: 59511722 (Raw.PeerUser) 1/4/2024 22:43:10.105
(@tgsnake/core) debug - [10] Reading TLObject with id: fd5ec8f5 (Raw.SendMessageCancelAction) 1/4/2024 22:43:10.105
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:10.105
(@tgsnake/core) debug - [37] Add msg id 7352909244682050561 to pending acks. 1/4/2024 22:43:10.105
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:10.105
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.105
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.105
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:10.105
(tgsnake) debug - Parsing update: UpdateChannelUserTyping 1/4/2024 22:43:10.105
1711982590105
{ _: 'Update' }
(@tgsnake/core) debug - [3] Receive 248 bytes data 1/4/2024 22:43:10.704
(@tgsnake/core) debug - [33] Unpacking 104 bytes packet. 1/4/2024 22:43:10.704
(@tgsnake/core) debug - [5] Decrypting 80 bytes data with AES-256-IGE 1/4/2024 22:43:10.705
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:10.706
(@tgsnake/core) debug - [10] Reading TLObject with id: e5bdf8de (Raw.UpdateUserStatus) 1/4/2024 22:43:10.706
(@tgsnake/core) debug - [10] Reading TLObject with id: edb93949 (Raw.UserStatusOnline) 1/4/2024 22:43:10.706
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:10.706
(@tgsnake/core) debug - [37] Add msg id 7352909247100553217 to pending acks. 1/4/2024 22:43:10.706
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:10.706
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.706
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.706
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:10.706
(tgsnake) debug - Parsing update: UpdateUserStatus 1/4/2024 22:43:10.706
1711982590706
{ _: 'Update' }
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:10.707
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:10.707
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [10] Reading TLObject with id: 8c88c923 (Raw.UpdateChannelUserTyping) 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [10] Reading TLObject with id: 59511722 (Raw.PeerUser) 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [10] Reading TLObject with id: fd5ec8f5 (Raw.SendMessageCancelAction) 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [37] Add msg id 7352909247209657345 to pending acks. 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.708
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.708
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:10.708
(tgsnake) debug - Parsing update: UpdateChannelUserTyping 1/4/2024 22:43:10.708
1711982590708
{ _: 'Update' }
(@tgsnake/core) debug - [3] Receive 148 bytes data 1/4/2024 22:43:10.902
(@tgsnake/core) debug - [33] Unpacking 136 bytes packet. 1/4/2024 22:43:10.903
(@tgsnake/core) debug - [5] Decrypting 112 bytes data with AES-256-IGE 1/4/2024 22:43:10.903
(@tgsnake/core) debug - [10] Reading TLObject with id: 74ae4240 (Raw.Updates) 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [10] Reading TLObject with id: 922e6e10 (Raw.UpdateReadChannelInbox) 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [37] Add msg id 7352909248121889793 to pending acks. 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [43] Handling update Updates. 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.904
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.904
(tgsnake) debug - Receive update: Updates 1/4/2024 22:43:10.904
(tgsnake) debug - Parsing update: UpdateReadChannelInbox 1/4/2024 22:43:10.904
1711982590905
{ _: 'Update' }
(@tgsnake/core) debug - [3] Receive 148 bytes data 1/4/2024 22:43:10.907
(@tgsnake/core) debug - [33] Unpacking 136 bytes packet. 1/4/2024 22:43:10.907
(@tgsnake/core) debug - [5] Decrypting 112 bytes data with AES-256-IGE 1/4/2024 22:43:10.907
(@tgsnake/core) debug - [10] Reading TLObject with id: 74ae4240 (Raw.Updates) 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [10] Reading TLObject with id: 922e6e10 (Raw.UpdateReadChannelInbox) 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [37] Add msg id 7352909248140006401 to pending acks. 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [43] Handling update Updates. 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.908
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:10.908
(tgsnake) debug - Receive update: Updates 1/4/2024 22:43:10.908
(tgsnake) debug - Parsing update: UpdateReadChannelInbox 1/4/2024 22:43:10.908
1711982590908
{ _: 'Update' }
(@tgsnake/core) debug - [3] Receive 132 bytes data 1/4/2024 22:43:11.13
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:11.13
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:11.13
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:11.14
(@tgsnake/core) debug - [10] Reading TLObject with id: c32d5b12 (Raw.UpdateDeleteChannelMessages) 1/4/2024 22:43:11.14
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:11.14
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:11.14
(@tgsnake/core) debug - [37] Add msg id 7352909248599231489 to pending acks. 1/4/2024 22:43:11.14
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:11.14
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:11.14
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:11.14
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:11.14
(tgsnake) debug - Parsing update: UpdateDeleteChannelMessages 1/4/2024 22:43:11.14
1711982591014
{ _: 'Update' }
(@tgsnake/core) debug - [3] Receive 132 bytes data 1/4/2024 22:43:11.134
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:11.134
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:11.134
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [10] Reading TLObject with id: 8c88c923 (Raw.UpdateChannelUserTyping) 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [10] Reading TLObject with id: 59511722 (Raw.PeerUser) 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [10] Reading TLObject with id: 16bf744e (Raw.SendMessageTypingAction) 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [37] Add msg id 7352909249087043585 to pending acks. 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [45] Sending 8 pending aks. 1/4/2024 22:43:11.135
(@tgsnake/core) debug - [50] Sending msg id 7352909248256278528 (MsgsAck), has 92 bytes message. 1/4/2024 22:43:11.136
(@tgsnake/core) debug - [4] Encrypting 128 bytes data with AES-256-IGE 1/4/2024 22:43:11.136
(@tgsnake/core) debug - [51] Sending 152 bytes payload. 1/4/2024 22:43:11.137
(@tgsnake/core) debug - [2] Sending 152 bytes data. 1/4/2024 22:43:11.137
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:11.137
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:11.137
(tgsnake) debug - Parsing update: UpdateChannelUserTyping 1/4/2024 22:43:11.137
1711982591137
{ _: 'Update' }
(@tgsnake/core) debug - [46] Clearing all pending acks 1/4/2024 22:43:11.137
(@tgsnake/core) debug - [3] Receive 132 bytes data 1/4/2024 22:43:11.826
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:11.826
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:11.826
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:11.827
(@tgsnake/core) debug - [10] Reading TLObject with id: c32d5b12 (Raw.UpdateDeleteChannelMessages) 1/4/2024 22:43:11.827
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:11.827
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:11.828
(@tgsnake/core) debug - [37] Add msg id 7352909251981952001 to pending acks. 1/4/2024 22:43:11.828
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:11.828
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:11.828
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:11.828
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:11.828
(tgsnake) debug - Parsing update: UpdateDeleteChannelMessages 1/4/2024 22:43:11.828
1711982591828
{ _: 'Update' }
(@tgsnake/core) debug - [3] Receive 280 bytes data 1/4/2024 22:43:13.55
(@tgsnake/core) debug - [33] Unpacking 136 bytes packet. 1/4/2024 22:43:13.55
(@tgsnake/core) debug - [5] Decrypting 112 bytes data with AES-256-IGE 1/4/2024 22:43:13.55
(@tgsnake/core) debug - [10] Reading TLObject with id: 74ae4240 (Raw.Updates) 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [10] Reading TLObject with id: 922e6e10 (Raw.UpdateReadChannelInbox) 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [37] Add msg id 7352909257190303745 to pending acks. 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [43] Handling update Updates. 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.57
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.57
(tgsnake) debug - Receive update: Updates 1/4/2024 22:43:13.57
(tgsnake) debug - Parsing update: UpdateReadChannelInbox 1/4/2024 22:43:13.58
1711982593058
{ _: 'Update' }
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:13.58
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:13.58
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:13.59
(@tgsnake/core) debug - [10] Reading TLObject with id: c32d5b12 (Raw.UpdateDeleteChannelMessages) 1/4/2024 22:43:13.59
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 1/4/2024 22:43:13.59
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:13.59
(@tgsnake/core) debug - [37] Add msg id 7352909257191628801 to pending acks. 1/4/2024 22:43:13.59
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:13.59
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.59
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.59
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:13.59
(tgsnake) debug - Parsing update: UpdateDeleteChannelMessages 1/4/2024 22:43:13.59
1711982593059
{ _: 'Update' }
(@tgsnake/core) debug - [3] Receive 132 bytes data 1/4/2024 22:43:13.467
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:13.467
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:13.467
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:13.468
(@tgsnake/core) debug - [10] Reading TLObject with id: 8c88c923 (Raw.UpdateChannelUserTyping) 1/4/2024 22:43:13.468
(@tgsnake/core) debug - [10] Reading TLObject with id: 59511722 (Raw.PeerUser) 1/4/2024 22:43:13.468
(@tgsnake/core) debug - [10] Reading TLObject with id: fd5ec8f5 (Raw.SendMessageCancelAction) 1/4/2024 22:43:13.469
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:13.469
(@tgsnake/core) debug - [37] Add msg id 7352909258644964353 to pending acks. 1/4/2024 22:43:13.469
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:13.469
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.469
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.469
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:13.469
(tgsnake) debug - Parsing update: UpdateChannelUserTyping 1/4/2024 22:43:13.469
1711982593469
{ _: 'Update' }
(@tgsnake/core) debug - [55] Ping to telegram server. 1/4/2024 22:43:13.661
(@tgsnake/core) debug - [50] Sending msg id 7352909256846213120 (PingDelayDisconnect), has 32 bytes message. 1/4/2024 22:43:13.661
(@tgsnake/core) debug - [4] Encrypting 64 bytes data with AES-256-IGE 1/4/2024 22:43:13.661
(@tgsnake/core) debug - [51] Sending 88 bytes payload. 1/4/2024 22:43:13.662
(@tgsnake/core) debug - [2] Sending 88 bytes data. 1/4/2024 22:43:13.662
(@tgsnake/core) debug - [3] Receive 100 bytes data 1/4/2024 22:43:13.729
(@tgsnake/core) debug - [33] Unpacking 88 bytes packet. 1/4/2024 22:43:13.730
(@tgsnake/core) debug - [5] Decrypting 64 bytes data with AES-256-IGE 1/4/2024 22:43:13.730
(@tgsnake/core) debug - [10] Reading TLObject with id: 347773c5 (Raw.Pong) 1/4/2024 22:43:13.730
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:13.730
(@tgsnake/core) debug - [35] Setting server time: 1711982595. 1/4/2024 22:43:13.730
(@tgsnake/core) debug - [42] Got Pong and msg id is: 7352909256846213120. 1/4/2024 22:43:13.730
(@tgsnake/core) debug - [3] Receive 132 bytes data 1/4/2024 22:43:13.742
(@tgsnake/core) debug - [33] Unpacking 120 bytes packet. 1/4/2024 22:43:13.743
(@tgsnake/core) debug - [5] Decrypting 96 bytes data with AES-256-IGE 1/4/2024 22:43:13.743
(@tgsnake/core) debug - [10] Reading TLObject with id: 78d4dec1 (Raw.UpdateShort) 1/4/2024 22:43:13.743
(@tgsnake/core) debug - [10] Reading TLObject with id: 8c88c923 (Raw.UpdateChannelUserTyping) 1/4/2024 22:43:13.743
(@tgsnake/core) debug - [10] Reading TLObject with id: 59511722 (Raw.PeerUser) 1/4/2024 22:43:13.743
(@tgsnake/core) debug - [10] Reading TLObject with id: 16bf744e (Raw.SendMessageTypingAction) 1/4/2024 22:43:13.743
(@tgsnake/core) debug - [34] Reveive 1 data. 1/4/2024 22:43:13.747
(@tgsnake/core) debug - [37] Add msg id 7352909260308599809 to pending acks. 1/4/2024 22:43:13.747
(@tgsnake/core) debug - [43] Handling update UpdateShort. 1/4/2024 22:43:13.747
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.747
(@tgsnake/core) debug - [76] Updating 0 peers 1/4/2024 22:43:13.747
(tgsnake) debug - Receive update: UpdateShort 1/4/2024 22:43:13.747
(tgsnake) debug - Parsing update: UpdateChannelUserTyping 1/4/2024 22:43:13.747
1711982593747
{ _: 'Update' }
```

**Comment by butthx** [comment]
Hi, I have fixed this bug by adding an option to always sync updates with Telegram.  This will call the getChannelDifference function every 30 seconds without updating the channel.  By adding this option, I hope to fix the bug you are experiencing.

```js
// tgsnake 3.1.0
const client = new Snake({
  experimental: {
    alwaysSync: true
  }
})
```

A little explanation why you don't get any more updates after 2 minutes of connecting to the Telegram server on a channel/supergroup that sends messages too often. In my opinion, this is a normal thing, because when Telegram sends updates in real time (say 10 messages per second continuously) it can flood our server (client) and lead to DoS on our server.  Therefore, to prevent this from happening, Telegram may limit sending updates to clients from busy channels/supergroups.

Thank You.

**Comment by butthx** [comment]
Hello @awdr74100, how are you. I'm back to check whether the updated version I released has fixed the problem on your side? 

If not, you can reopen this issue and start discussing again.

I hope everything works normally and this bug is resolved. I am waiting for a reply from you, thank you.

**Comment by grinry** [comment]
I'm having same issue with some of the channels, looks like mostly supergroups.
But it stops receiving messages after 3-4 days of running instead of your suggested 2 minutes.

I did not had debug enabled so have no logs here. Collecting data now, hopefully I will be able to find some anomalies in day worth of logs.

@butthx

**Comment by butthx** [comment]
> I'm having same issue with some of the channels, looks like mostly supergroups. But it stops receiving messages after 3-4 days of running instead of your suggested 2 minutes.
> 
> I did not had debug enabled so have no logs here. Collecting data now, hopefully I will be able to find some anomalies in day worth of logs.
> 
> @butthx

Did you find any anomalies? i tried to implement read message when there is a new message but it didn't help.

Look like this issue happened on telegram web too.

![IMG_20240414_070426](https://github.com/tgsnake/tgsnake/assets/68604099/9885b5f1-ef47-4738-88f1-9228d1bc20a5)

On telegram app (Android): 
![IMG_20240414_070330](https://github.com/tgsnake/tgsnake/assets/68604099/57d278e0-5f88-4a25-9514-0515bfa1d945)

On the same group, it has different update between 2 client app.

**Comment by grinry** [comment]
Unfortunately no. Have two instances running at the moment, one is with experimental `alwaysSync` enabled - which looks like still receiving messages now (but it's 3rd day, so waiting to see if it stop doing it soon).

Another one is without `alwaysSync` - but it's being connected just for couple minutes using cron to detect messages on a supergroup which was scheduled to appear on certain time.
For some reason messages from that supergroup does not get detected (same code worked a week ago). 
I still detect messages from other groups but not from that certain one for some reason and logs does not show anything out of ordinary.

**Comment by butthx** [comment]
_There doesn't seem to be any updates on this issue, I'll close it and mark as resolved. You can reopen this issue if this solution is not helped_

# Summary
- Many people report their app can't receive update after few minutes client running.
- This problem is only happened on flooded channel or supergroup.
- In several tests, the official Telegram application (web) also experienced the same thing.
- Updates will appear again when the channel or supergroup is opened and marked as read. For that, it is necessary to call `getChannelDifference` every once in a while. Like the `openChat` function in TDLib.
- On new version (stable ^3.1.0) tgsnake has implemented `alwaysSync` function which will then call the getChannelDifference function periodically.

```js
// config
{
  experimental: {
   alwaysSync: true
  }
}
```
## Solution 
Update to the latest version and add the `experimental.alwaySync` option in your configuration. 

```diff
// tgsnake.config.js
const config = {
+  experimental: {
+    alwaysSync: true
+  }
}
module.exports = config
```
